// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZOQK6BaL7MYWzCjnI1_XVCmo5k7LddZU',
    appId: '1:269970505996:web:4bc67cf4a1772218074929',
    messagingSenderId: '269970505996',
    projectId: 'first-flutter-project-86e84',
    authDomain: 'first-flutter-project-86e84.firebaseapp.com',
    storageBucket: 'first-flutter-project-86e84.firebasestorage.app',
    measurementId: 'G-4P54PBWCM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9wD1bF6F1g6LqeBe7RmQAN7FFRoE6WKg',
    appId: '1:269970505996:android:b64917090613094c074929',
    messagingSenderId: '269970505996',
    projectId: 'first-flutter-project-86e84',
    storageBucket: 'first-flutter-project-86e84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp_glS-FaSmFXSmXEfFOVfkLDoCVP7DAs',
    appId: '1:269970505996:ios:6cf27a8724707e33074929',
    messagingSenderId: '269970505996',
    projectId: 'first-flutter-project-86e84',
    storageBucket: 'first-flutter-project-86e84.firebasestorage.app',
    androidClientId: '269970505996-tb45dc8qibbsg8e9iq9pj8pjtdj7dkil.apps.googleusercontent.com',
    iosClientId: '269970505996-7c230jn06b9g53bddfp7png4rfgiv5vo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleSignIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp_glS-FaSmFXSmXEfFOVfkLDoCVP7DAs',
    appId: '1:269970505996:ios:6cf27a8724707e33074929',
    messagingSenderId: '269970505996',
    projectId: 'first-flutter-project-86e84',
    storageBucket: 'first-flutter-project-86e84.firebasestorage.app',
    androidClientId: '269970505996-tb45dc8qibbsg8e9iq9pj8pjtdj7dkil.apps.googleusercontent.com',
    iosClientId: '269970505996-7c230jn06b9g53bddfp7png4rfgiv5vo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleSignIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZOQK6BaL7MYWzCjnI1_XVCmo5k7LddZU',
    appId: '1:269970505996:web:8efb800dfd0d64de074929',
    messagingSenderId: '269970505996',
    projectId: 'first-flutter-project-86e84',
    authDomain: 'first-flutter-project-86e84.firebaseapp.com',
    storageBucket: 'first-flutter-project-86e84.firebasestorage.app',
    measurementId: 'G-EXC8HHNHX3',
  );
}
